### ISSUE TITLE
Plugin does not work with Cura version 5.0.0-beta+1

### ISSUE THREAD

**Issue by DavidKahnt** [rgomezjnr/GcodeFilenameFormatPlus#10]
Are there any plans supporting Cura version 5?

**Comment by rgomezjnr** [comment]
Hi David I'll have to familiarize myself with the changes in 5 and see if there's any API differences. If 5 continues to support the existing Cura Marketplace and doesn't have any significant compatibility issues GFF+ will probably work in 5 as is.

**Comment by rgomezjnr** [comment]
What specifically doesn't work? Does the plugin not load on startup?

**Comment by MichaelSordje** [comment]
Yes, it does not load on startup

**Comment by MichaelSordje** [comment]
found the log entries:

2022-05-18 18:35:28,910 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: Exception: Import error loading module GcodeFilenameFormatPlus
2022-05-18 18:35:28,911 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: Traceback (most recent call last):
2022-05-18 18:35:28,912 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "UM\PluginRegistry.py", line 728, in _findPlugin
2022-05-18 18:35:28,912 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     module = imp.load_module(plugin_id, file, path, desc)  # type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2022-05-18 18:35:28,913 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "imp.py", line 245, in load_module
2022-05-18 18:35:28,913 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "imp.py", line 217, in load_package
2022-05-18 18:35:28,913 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 719, in _load
2022-05-18 18:35:28,913 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-18 18:35:28,914 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-18 18:35:28,914 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-18 18:35:28,914 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "C:\Users\Speedy\AppData\Roaming\cura\5.0\plugins\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus\__init__.py", line 3, in <module>
2022-05-18 18:35:28,915 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from . import GcodeFilenameFormatPlus
2022-05-18 18:35:28,915 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "C:\Users\Speedy\AppData\Roaming\cura\5.0\plugins\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus.py", line 8, in <module>
2022-05-18 18:35:28,915 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from PyQt5.QtCore import QUrl, Qt, QDate, QDateTime
2022-05-18 18:35:28,916 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: ModuleNotFoundError: No module named 'PyQt5'
2022-05-18 18:35:28,916 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [822]: Could not find plugin GcodeFilenameFormatPlus
2022-05-18 18:35:28,920 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: Exception: Import error loading module GcodeFilenameFormatPlus
2022-05-18 18:35:28,920 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: Traceback (most recent call last):
2022-05-18 18:35:28,921 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "UM\PluginRegistry.py", line 728, in _findPlugin
2022-05-18 18:35:28,921 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     module = imp.load_module(plugin_id, file, path, desc)  # type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2022-05-18 18:35:28,921 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "imp.py", line 245, in load_module
2022-05-18 18:35:28,922 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "imp.py", line 217, in load_package
2022-05-18 18:35:28,922 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 719, in _load
2022-05-18 18:35:28,922 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-18 18:35:28,923 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-18 18:35:28,923 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-18 18:35:28,923 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "C:\Users\Speedy\AppData\Roaming\cura\5.0\plugins\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus\__init__.py", line 3, in <module>
2022-05-18 18:35:28,924 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from . import GcodeFilenameFormatPlus
2022-05-18 18:35:28,924 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "C:\Users\Speedy\AppData\Roaming\cura\5.0\plugins\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus\GcodeFilenameFormatPlus.py", line 8, in <module>
2022-05-18 18:35:28,924 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from PyQt5.QtCore import QUrl, Qt, QDate, QDateTime
2022-05-18 18:35:28,925 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: ModuleNotFoundError: No module named 'PyQt5'
2022-05-18 18:35:28,926 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [527]: Exception: Error loading plugin GcodeFilenameFormatPlus:
2022-05-18 18:35:28,926 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [527]: NoneType: None

**Comment by DavidKahnt** [comment]
> Yes, it does not load on startup

As @Speedy75 already mentioned, the plugin does not load at the Cura startup. Sorry for the delay and thanks for helping out with the error log.

**Comment by rgomezjnr** [comment]
Hey guys this is what I found from a quick search:

https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/

> With the release of the Cura 5.0 beta, a lot has changed in the core of Cura. So much so, that in order to be compatible with Cura 5.0, all plugin need to be updated and resubmitted to the Marketplace. 

It will take me a while to review the changes in 5 to make GFF+ compatible with it. The changes might be drastic so it might entail a complete rewrite of this plugin.

For now I recommend manually deleting the GFF+ plugin folder if you really want to use Cura 5.

**Comment by rgomezjnr** [comment]
Hey guys I submitted GFF+1.0.0 to the Marketplace for evaluation. It should be available for download in the Cura 5 Marketplace soon once it gets approved.

**Comment by rgomezjnr** [comment]
If you want to try it out before it's released here's the plugin zip: [GcodeFilenameFormatPlus-1.0.0.zip](https://github.com/rgomezjnr/GcodeFilenameFormatPlus/files/8987786/GcodeFilenameFormatPlus-1.0.0.zip)

https://github.com/rgomezjnr/GcodeFilenameFormatPlus/tree/cura5#alternatively

**Comment by JeffFaer** [comment]
Looks like it got approved. Thanks Robert!

https://marketplace.ultimaker.com/app/cura/plugins/rgomezjnr/GcodeFilenameFormatPlus?action=addToCura

**Comment by rgomezjnr** [comment]
Here's the release notes:

https://github.com/rgomezjnr/GcodeFilenameFormatPlus/releases/tag/1.0.0
